# Generated by Django 4.1.3 on 2022-11-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import projects.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("token_auth", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, validators=[projects.validators.ProjectNameValidator()]
                    ),
                ),
                ("is_public", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "permissions",
                    models.ManyToManyField(
                        limit_choices_to=models.Q(
                            (
                                "codename__in",
                                ["add_project", "change_project", "delete_project", "view_project", "add_legacyupload"],
                            )
                        ),
                        to="auth.permission",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
                (
                    "token",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="token_auth.authtoken"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectpermission",
            constraint=models.CheckConstraint(
                check=models.Q(("user__isnull", False), ("token__isnull", False), _connector="XOR"),
                name="projects_projectpermission_user_or_token_required",
            ),
        ),
    ]
